# Generated by Django 6.1.1 on 2026-09-26 19:57

import django.db.models.deletion
import django.utils.timezone
import sheets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greensheet',
            name='flip_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flip_side', to='sheets.greensheet'),
        ),
        migrations.AddField(
            model_name='person',
            name='session_epoch',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('sheet.created', 'greensheet created'), ('sheet.edited', 'greensheet edited'), ('sheet.archived', 'greensheet archived'), ('sheet.unarchived', 'greensheet unarchived'), ('sheet.deleted', 'greensheet deleted'), ('item.created', 'item added'), ('item.edited', 'item edited'), ('item.completed', 'item completed'), ('item.reopened', 'item reopened'), ('item.deleted', 'item deleted'), ('invite.sent', 'invite sent'), ('invite.accepted', 'invite accepted'), ('invite.declined', 'invite declined'), ('link.issued', 'sign-in link sent'), ('link.consumed', 'signed in'), ('digest.on', 'daily summary turned on'), ('digest.off', 'daily summary turned off'), ('digest.sent', 'daily summary sent'), ('token.created', 'API token created'), ('person.deleted', 'person deleted'), ('flip.created', 'flip side created'), ('session.revoked', 'signed out everywhere'), ('webhook.created', 'webhook created'), ('webhook.deleted', 'webhook deleted')], max_length=40),
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('secret', models.CharField(default=sheets.models.new_token, max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.IntegerField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
