# Generated by Django 6.1.1 on 2026-09-29 14:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_flip_side_webhooks_epoch'),
    ]

    operations = [
        migrations.AddField(
            model_name='greensheet',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('greensheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='sheets.greensheet')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('greensheet', 'person'), name='visit_unique')],
            },
        ),
    ]
